---
engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
  watson:
    enabled: true
ratings:
  paths:
  - "app/**"
  - "addon/**"
  - "blueprints/**"
exclude_paths:
- "*.md"
- "config/**"
- "dist/**"
- "vendor/**"
- "node_modules/**"
- "bower_components/**"
- "tmp/**"
